# Generated by Django 6.0.2 on 2026-02-27 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiSelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='analytics.questioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('age', models.IntegerField(blank=True, db_index=True, null=True)),
                ('gender', models.CharField(db_index=True, max_length=50)),
                ('sub_city', models.CharField(db_index=True, max_length=100)),
                ('education', models.CharField(db_index=True, max_length=255)),
                ('employment', models.CharField(db_index=True, max_length=100)),
                ('telegram_account', models.BooleanField(default=False)),
                ('heard_about_yne', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['gender'], name='analytics_r_gender_df0f25_idx'), models.Index(fields=['education'], name='analytics_r_educati_d4c082_idx'), models.Index(fields=['employment'], name='analytics_r_employm_304866_idx')],
            },
        ),
        migrations.CreateModel(
            name='MultiSelectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='analytics.multiselectoption')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_answers', to='analytics.respondent')),
            ],
        ),
        migrations.AddIndex(
            model_name='multiselectoption',
            index=models.Index(fields=['category'], name='analytics_m_categor_19dd7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='multiselectoption',
            unique_together={('category', 'value')},
        ),
        migrations.AddIndex(
            model_name='multiselectanswer',
            index=models.Index(fields=['respondent'], name='analytics_m_respond_4cd5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='multiselectanswer',
            index=models.Index(fields=['option'], name='analytics_m_option__bbc31d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='multiselectanswer',
            unique_together={('respondent', 'option')},
        ),
    ]
