# Generated by Django 6.0.2 on 2026-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='respondent',
            index=models.Index(fields=['age'], name='analytics_r_age_02cd81_idx'),
        ),
        migrations.AddIndex(
            model_name='respondent',
            index=models.Index(fields=['sub_city'], name='analytics_r_sub_cit_0128bc_idx'),
        ),
    ]
